"""Port — Berechtigungsprofil-Persistenz (Gate 8.1b)."""

from __future__ import annotations

from typing import Protocol

from domain.identity.berechtigungsprofil import Berechtigungsprofil


class BerechtigungsprofilRepository(Protocol):
    def save(self, profil: Berechtigungsprofil) -> None: ...

    def get(self, profil_id: str) -> Berechtigungsprofil | None: ...

    def list_all(self) -> list[Berechtigungsprofil]: ...

    def delete(self, profil_id: str) -> None: ...

    def profil_ids_fuer_benutzer(self, benutzer_id: str) -> frozenset[str]: ...

    def benutzer_zuordnen(self, *, profil_id: str, benutzer_id: str) -> None: ...

    def benutzer_entfernen(self, *, profil_id: str, benutzer_id: str) -> None: ...

    def profile_fuer_benutzer(self, benutzer_id: str) -> list[Berechtigungsprofil]: ...
