"""Ports — Katalog-Bibliothek (Facade für Bibliotheksobjekte)."""

from __future__ import annotations

from typing import Protocol

from domain.katalog.externes_kommando import ExternesKommando
from domain.katalog.pruefschritt_vorlage import PruefschrittVorlage
from domain.katalog.routine import Routine


class BibliothekRepository(Protocol):
    def save_externes_kommando(self, kommando: ExternesKommando) -> None: ...

    def get_externes_kommando(self, kommando_id: str) -> ExternesKommando | None: ...

    def save_routine(self, routine: Routine) -> None: ...

    def get_routine(self, routine_id: str) -> Routine | None: ...

    def save_pruefschritt_vorlage(self, vorlage: PruefschrittVorlage) -> None: ...

    def get_pruefschritt_vorlage(self, vorlage_id: str) -> PruefschrittVorlage | None: ...

    def list_externe_kommandos(self) -> list[ExternesKommando]: ...

    def list_routinen(self) -> list[Routine]: ...

    def list_pruefschritt_vorlagen(self) -> list[PruefschrittVorlage]: ...

    def delete_externes_kommando(self, kommando_id: str) -> None: ...

    def delete_routine(self, routine_id: str) -> None: ...

    def delete_pruefschritt_vorlage(self, vorlage_id: str) -> None: ...
